package edu.neumont.csc250.sorting;

import static org.junit.jupiter.api.Assertions.*;

import edu.neumont.csc250.sorting.data.DataGenerator;
import org.junit.jupiter.api.*;

import java.util.ArrayList;

/**
 * https://junit.org/junit5/docs/current/user-guide/
 * use @Disabled("Reason disabled") above a test to disable it in the run
 *
 */
class SortingLibraryTest {
    //Seed ensures Random always generates same numbers
    private static final int SEED = 12271978;

    @Test
    void bubbleSortOnRandomArrayOf100() {
        //Assemble
        Integer[] randList = DataGenerator.generateRandomInts(SEED, 100);
        Integer[] sorted = DataGenerator.generateAscendingInts(SEED, 100);

        //Act
        SortingLibrary.bubbleSort(randList);

        //Assert
        assertArrayEquals(sorted, randList);
    }

    @Test
    void bubbleSortCanSortBasicArray(){
        //Arrange
        Integer[] arr = {1, 4, 2, 5, 3};
        Integer[] expected = {1, 2, 3, 4, 5};

        //Act
        SortingLibrary.bubbleSort(arr);

        //Assert
        assertArrayEquals(expected, arr);
    }

    @Test
    void bubbleSortHandlesEmptyArray(){
        //Arrange
        Integer[] arr = {};
        Integer[] expected = {};

        //Act
        SortingLibrary.bubbleSort(arr);

        //Assert
        assertArrayEquals(expected, arr);
    }

    @Test
    //[ExpectedException(NullReferenceException)]
    void bubbleSortHandlesNullArray(){
        //Arrange
        Integer[] arr = null;

        //Act & Assert
        assertThrows(NullPointerException.class, () -> SortingLibrary.bubbleSort(arr));
    }

    @Test
    void selectionSortSortsBasicArray(){
        Integer[] arr = {2,4,3,1,5,8,6,9,7,10};
        Integer[] expected = {1,2,3,4,5,6,7,8,9,10};

        SortingLibrary.selectionSort(arr);

        assertArrayEquals(expected, arr);
    }

    @Test
    void selectionSortHandlesEmptyArray(){
        Integer[] arr = {};
        Integer[] expected = {};

        SortingLibrary.selectionSort(arr);

        assertArrayEquals(expected, arr);
    }

    @Test
    void selectionSortHandlesRepeatingValues(){
        Integer[] arr = {2,2,2,2,2};
        Integer[] expected = {2,2,2,2,2};

        SortingLibrary.selectionSort(arr);

        assertArrayEquals(expected, arr);
    }

    @Test
    void selectionSortHandlesSingleValue(){
        Integer[] arr = {1};
        Integer[] expected = {1};

        SortingLibrary.selectionSort(arr);

        assertArrayEquals(expected, arr);
    }

    @Test
    void selectionSortReverseSortedArray(){
        Integer[] arr = {10,9,8,7,6,5,4,3,2,1};
        Integer[] expected = {1,2,3,4,5,6,7,8,9,10};

        SortingLibrary.selectionSort(arr);

        assertArrayEquals(expected, arr);
    }

    //this method was generated by Gemini
    @Test
    void selectionSortHandlesNegativeNumbers(){
        Integer[] arr = {2, -4, 3, -1, 0};
        Integer[] expected = {-4, -1, 0, 2, 3};

        SortingLibrary.selectionSort(arr);

        assertArrayEquals(expected, arr);
    }

//    @Test no longer applicable with another for loop
//    void insertionSortHandlesOnePass(){
//        Integer[] arr = {4,2,3,1,5,8,6,9,7,10};
//        Integer[] expected = {2,4,3,1,5,8,6,9,7,10};
//
//        SortingLibrary.insertionSort(arr);
//
//        assertArrayEquals(expected, arr);
//    }

    @Test
    void insertionSortHandlesBasicArray(){
        Integer[] arr = {2,4,3,1,5,8,6,9,7,10};
        Integer[] expected = {1,2,3,4,5,6,7,8,9,10};

        SortingLibrary.insertionSort(arr);

        assertArrayEquals(expected, arr);
    }

    //this method was generated by Gemini
    @Test
    void insertionSortHandlesNegativeNumbers(){
        Integer[] arr = {2, -4, 3, -1, 0};
        Integer[] expected = {-4, -1, 0, 2, 3};

        SortingLibrary.insertionSort(arr);

        assertArrayEquals(expected, arr);
    }

    @Test
    void insertionSortHandlesEmptyArray(){
        Integer[] arr = {};
        Integer[] expected = {};

        SortingLibrary.insertionSort(arr);

        assertArrayEquals(expected, arr);
    }

    @Test
    void insertionSortHandlesASingleItem(){
        Integer[] arr = {1};
        Integer[] expected = {1};

        SortingLibrary.insertionSort(arr);

        assertArrayEquals(expected, arr);
    }

    @Test
    void insertionSortHandlesRepeatingValues(){
        Integer[] arr = {1,1,1,1,1,1,1};
        Integer[] expected = {1,1,1,1,1,1,1};

        SortingLibrary.insertionSort(arr);

        assertArrayEquals(expected, arr);
    }

    @Test
    void insertionSortReverseSortedArray(){
        Integer[] arr = {10,9,8,7,6,5,4,3,2,1};
        Integer[] expected = {1,2,3,4,5,6,7,8,9,10};

        SortingLibrary.insertionSort(arr);

        assertArrayEquals(expected, arr);
    }

    @Test
    void binarySearchFindsIndexInBasicArrayTest()
    {
        //Arrange
        int[] numberList = {2, 5, 10, 11, 25, 50};
        int expectedIndex = 4;
        int findNumber = numberList[expectedIndex];

        //Act
        int actualIndex = SortingLibrary.binarySearch(numberList, findNumber, 0, numberList.length - 1);

        //Assert
        assertEquals(expectedIndex, actualIndex);
    }

    @Test
    void binarySearchCanFindValueGoingLeft()
    {
        //Arrange
        int[] numberList = {2, 5, 10, 11, 25, 50};
        int expectedIndex = 0;
        int findNumber = numberList[expectedIndex];

        //Act
        int actualIndex = SortingLibrary.binarySearch(numberList, findNumber, 0, numberList.length - 1);

        //Assert
        assertEquals(expectedIndex, actualIndex);
    }

    @Test
    void binarySearchBestCaseScenario()
    {
        //Arrange
        int[] numberList = {2, 5, 10, 11, 25, 50};
        int expectedIndex = 2;
        int findNumber = numberList[expectedIndex];

        //Act
        int actualIndex = SortingLibrary.binarySearch(numberList, findNumber, 0, numberList.length - 1);

        //Assert
        assertEquals(expectedIndex, actualIndex);
    }

    @Test
    void binarySearchWithNegativeValues()
    {
        //Arrange
        int[] numberList = {-20, -9, -1, 4, 9, 20};
        int expectedIndex = 1;
        int findNumber = numberList[expectedIndex];

        //Act
        int actualIndex = SortingLibrary.binarySearch(numberList, findNumber, 0, numberList.length - 1);

        //Assert
        assertEquals(expectedIndex, actualIndex);
    }

    @Test
    void binarySearchWithEmptyArray()
    {
        //Arrange
        int[] numberList = {};
        int expectedIndex = -1;
        int findNumber = 0;

        //Act
        int actualIndex = SortingLibrary.binarySearch(numberList, findNumber, 0, numberList.length - 1);

        //Assert
        assertEquals(expectedIndex, actualIndex);
    }

//    @Test
//    void mergeMethodWorksProperly()
//    {
//        Integer[] numbers = {7,1,8,4,5,6,2,3};
//        Integer[] left = {1,4,7,8};
//        Integer[] right = {2,3,5,6};
//        Integer[] expected = {1,2,3,4,5,6,7,8};
//
//        SortingLibrary.merge(numbers, left, right);
//
//        assertArrayEquals(expected, numbers);
//    }

    // Merge Sort Tests
    @Test
    void mergeSortWorksOnBasicArray(){
        Integer[] nums = {7,1,8,4,5,6,2,3};
        Integer[] expected = {1,2,3,4,5,6,7,8};

        SortingLibrary.mergeSort(nums);

        assertArrayEquals(expected, nums);
    }

    @Test
    void mergeSortWorksWithDuplicateNumbers(){
        Integer[] nums = {7,1,8,4,7,6,2,3};
        Integer[] expected = {1,2,3,4,6,7,7,8};

        SortingLibrary.mergeSort(nums);

        assertArrayEquals(expected, nums);
    }

    @Test
    void mergeSortHandlesEmptyArray(){
        Integer[] nums = {};
        Integer[] expected = {};

        SortingLibrary.mergeSort(nums);

        assertArrayEquals(expected, nums);
    }

    @Test
    void mergeSortHandlesArrayWithOneItem(){
        Integer[] nums = {1};
        Integer[] expected = {1};

        SortingLibrary.mergeSort(nums);

        assertArrayEquals(expected, nums);
    }

//    @Test
//    void partitionWorksForOnePass(){
//        Integer[] nums = {3,6,9,4,8,1,7,5,2,10};
//        Integer[] expected = {2,1,3,4,8,9,7,5,6,10};
//
//        SortingLibrary.partition(nums, 0, nums.length - 1);
//
//        assertArrayEquals(expected, nums);
//    }

    // Quick sort tests
    @Test
    void quickSortSortsBasicArray(){
        Integer[] nums = {3,6,9,4,8,1,7,5,2,10};
        Integer[] expected = {1,2,3,4,5,6,7,8,9,10};

        SortingLibrary.quickSort(nums, 0, nums.length - 1);

        assertArrayEquals(expected, nums);
    }

    @Test
    void quickSortsDuplicateValues(){
        Integer[] nums = {10,2,7,4,10,6,3,8,2,5};
        Integer[] expected = {2,2,3,4,5,6,7,8,10,10};

        SortingLibrary.quickSort(nums, 0, nums.length - 1);

        assertArrayEquals(expected, nums);
    }

    @Test
    void quickSortHandlesEmptyArray(){
        Integer[] nums = {};
        Integer[] expected = {};

        SortingLibrary.quickSort(nums, 0, nums.length - 1);

        assertArrayEquals(expected, nums);
    }

    @Test
    void quickSortHandlesAnArrayWithOneValue(){
        Integer[] nums = {1};
        Integer[] expected = {1};

        SortingLibrary.quickSort(nums, 0, nums.length - 1);

        assertArrayEquals(expected, nums);
    }

    //Methods generated by Gemini
    @Test
    void mergeSortHandlesReverseSortedArray(){
        Integer[] nums = {10, 9, 8, 7, 6, 5, 4, 3, 2, 1};
        Integer[] expected = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10};

        SortingLibrary.mergeSort(nums);

        assertArrayEquals(expected, nums);
    }

    @Test
    void quickSortHandlesReverseSortedArray(){
        Integer[] nums = {10, 9, 8, 7, 6, 5, 4, 3, 2, 1};
        Integer[] expected = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10};

        SortingLibrary.quickSort(nums, 0, nums.length - 1);

        assertArrayEquals(expected, nums);
    }

}
